import { NavbarLat } from '@/components/navbar/NavbarLat'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className='flex' >
          <div className='h-screen w-2/12 bg-primary' >
            <NavbarLat />

          </div>
          <main className='w-10/12'>
            {children}
          </main>
        </div>

      </body>
    </html>
  )
}
