import { NavbarLat } from '@/components/navbar/NavbarLat'
import localFont from 'next/font/local'
import './globals.css'

const sfpro = localFont({
  src: [

    {
      path: '../fonts/sf-pro-text/SFProText-Regular.ttf',
      weight: '400',
      style: 'normal',
    
    },
    {
      path: '../fonts/sf-pro-text/SFProText-Semibold.ttf',
      weight: '600',
      style: 'normal',
    }
  
  ],
  
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={sfpro.className}>
        <div className='flex gap-2' >
          <div className='h-screen w-2/12 bg-primary' >
            <NavbarLat />

          </div>
          <main className='w-8/12'>
            <div className='p-8 max-w-5xl flex flex-col min-h-screen' >
              {children}

            </div>
          </main>
        </div>

      </body>
    </html>
  )
}
